### PR TITLE
Create an FAQ / How do I... ? page

### PR DESCRIPTION
**Pull request by radiatoryang**
Started working on an FAQ / cookbook page. Would be good to direct people to this for common questions and problems.

Is this something the YS team might want? Or no?

### CODE REVIEW

**Comment by KXI-System** [comment]
As requested from the discord, here are some more FAQs found in the help channel:


_How do I change the LineView or OptionListView?_
This usually comes from users who are new to using Unity Packages, but the answer usually involves explaining Dialogue Views and the possibility of making your own.

_How do I continue the story with key/button press instead of the continue button?_
The answer is basically use the `DialogueAdvanceInput.cs` script, but calling `UserRequestedViewAdvancement` on any view or `OnContinueClicked` specifically on the LineView are valid answers too. Most are satisfied with the first answer though.

_How do I show a C# variable in my yarn story?_
Basically yarn functions and explaining a basic way to set that up.

_How do I change a yarn variable in C#?_
_How do I change a C# variable in yarn?_
Not asked too much anymore, but a simple code snippet is enough.

_How do I "sync" a variable between my yarn story and C# script?_
This comes from not knowing its possible to access a C# variable in yarn and vice versa. Basically answered in the previous two questions, but extra explanation on why its bad to have the same variable in two places and where the variable should live.

_How do I show the last seen line of text when the options are shown?_
_How do I skip the last line of text before a set of options?_
Basically a modified LineView that uses the `#lastline` tag to do what's wanted, though this might be better as a feature added to LineView by now. It could also be a good idea to have a guide to modify the existing views and have this be the feature added.

_How do I start a dialogue from a node?_
_How do I start a dialogue while another node is running?_
It's just `StartDialogue`

_How to save a dialogue "history"?_
A feature where previous seen lines are displayed to the player, this could be a guide by itself explaining the concept of line IDs as well.

_How do I jump to a specific line in a node?_
This is usually for the purpose of having a VN style saving and loading.

_How do I display a specific line from a node?_
This is usually for line descriptions or using YarnSpinner as a localization tool.

_How do I use Yarn Markup?_
This is better off being an entire guide.

_How do I create a yarn project during runtime?_
Rarely asked, and its either a misunderstanding on how to use Yarn Projects or a niche use case.

_How many yarn files should I have?_
_Can my entire story be in one yarn project/file?_
_Should I have a yarn project for each scene?_
_Is my yarn project/file too big?_ 
Some helpful tips about yarn projects and yarn files will help answer these questions.

_How should I stop my dialogue while its still running?_
_Why doesn't `DialogueRunner.Stop` work?_
Part of a bigger discussion on `DialogueRunner.Stop` but basically outlining a way to stop the dialogue runner _and_ the views.

**Comment by radiatoryang** [comment]
OK, there's probably some broken links, and/or bad info, but it's 90% of the way there

Would appreciate feedback and/or edits, thanks!

**Comment by radiatoryang** [comment]
OK I think this initial version is ready for review! It's not exhaustive, but it has a lot of info and will help a lot of people I think

https://github.com/radiatoryang/YSDocs/blob/patch-1/using-yarnspinner-with-unity/faq.md

**Comment by desplesda** [comment]
Updated this PR to the current state of the `staging` branch, and did a pass over this!

Main changes:
- Replaced http links to docs pages to in-repo references
- Removed link to PR 242 regarding saving/loading dialogue state (we're not sure that we'll end up implementing this feature, so including it in the FAQ may set up bad expectations.)

Overall, this is absolutely fantastic! If you're happy with my changes, I can merge this and get it added to the site.

**Comment by radiatoryang** [comment]
lgtm thanks!

**Pull request merged**
